export const ROUTES = {
  home: "/",
  essayMarking: "/essay-marking",
  login: "/login",
  register: "/register",
  assignmentPending: "/waiting-assignment",
  dashboard: "/dashboard",
  classes: "/classes",
  electives: "/electives",
  service: "/service",
  notifications: "/notifications",
  profile: "/profile",
  wrongBook: "/wrong-book",
  admin: "/admin",
  adminTasks: "/admin/tasks",
} as const;
